### ISSUE TITLE
Receives an alert window error "There was an error loading a required file. Would you like to reload the page to try to load again?"

### ISSUE THREAD

**Issue by joncloud** [nnessen/VstsOpenPullRequests#1]
## Symptom
Received an alert window prompting for "There was an error loading a required file. Would you like to reload the page to try to load again?"
Simultaneously a console error message is printed "Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.vsassets.io/v/20180524T184218/_cssbundles/Default/vss-bundle-commoncss-vUI1xE73yBC018_fifA6N7RrfA-QB84zThKkhVGUlwuk=' with computed SHA-256 integrity 'cMjcYtmSkLDZYK3TphkOp8J2eaZGNQhFF80+VqgOz+s='. The resource has been blocked."

## Steps to Reproduce
Open any URL under https://*.visualstudio.com
It appears that if the asset that is downloaded becomes cached, the prompt no longer shows. The cache does not appear to be valid for a long time. Running a new sandboxed environment (incognito, private mode, etc.) results in the error message every time.

### Operating System
Windows 10 Version 1703 (OS Build 15063.966)

### Browser
Chrome Version 66.0.3359.181 (Official Build) (64-bit)
Firefox Developer Edition 61.0b7 (64-bit)

**Comment by nnessen** [comment]
This seems like it would most likely be from `usePlatformStyles: true` in `boot.ts`.  Not sure what we can do about that at this point.

**Comment by nnessen** [comment]
This was an issue in VSTS and is no longer being experienced.
